apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o komposefiles/ --volumes hostPath
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-tcp
  name: mysql-tcp
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3307
  selector:
    io.kompose.service: mysql
  type: LoadBalancer
status:
  loadBalancer: {}
